# Generated by Django 5.2.4 on 2025-08-09 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('post_id', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogpost_user', models.CharField(max_length=200)),
                ('blogpost_title', models.CharField(max_length=200)),
                ('blogpost_text', models.TextField()),
                ('blogpost_author', models.CharField(max_length=50)),
                ('blogpost_likes', models.IntegerField(default=0)),
                ('blogpost_comments', models.IntegerField(default=0)),
                ('blogpost_shares', models.IntegerField(default=0)),
                ('blogpost_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
